src/provider.ts
tests/integration/provider.test.ts

Removes support for `zks_getConfirmedTokens`
This method doesn't have any usage on mainnet, it doesn't have a well-established practical meaning as well. So, it's going to be removed from the main node soon.

feat: Remove zks_getConfirmedTokens method

---

.github/workflows/validate.yml
README.md

* Add conditional step in validation pipeline that checks commit messages from fork repositories.
* Contributors needs to follow conventional commits.

ci: configure `commitlint` to check commits from forks

---

src/wallet.ts

* avoid adding gasPrice in eip-1559 transaction request
* I meet the error "eip-1559 transaction do not support gasPrice", when integrating mute paymaster with zksync-ethers@5.3.0. After debug, I find the populateTransaction method always add gasPrice for transactionRequest even it is eip-1559 transaction, which result into error report in ethers@5 side.
* Co-author : samzkback <geeksam820@gmail.com>
* Co-author : Connor Leigh-Smith <connorbob21@gmail.com>

fix : "eip-1559 transaction do not support gasPrice"

---

src/wallet.ts

tl;dr this fixes a bug causing `TypeError: eip-1559 transaction do not support gasPrice` to be thrown unexpectedly. Steps to reproduce bug:
- Craft a transaction manually with `maxFeePerGas` or `maxPriorityFeePerGas` set, as well as the `customData` field (in my case, for trying Paymaster).
- Sign and broadcast this transaction with `wallet.sendTransaction(tx)`
The issue is, `sendTransaction` calls `this.populateTransaction` which currently succeeds and adds `gasPrice` to the transaction. Then, `sendTransaction` calls `this.signTransaction` which again calls `this.populateTransaction`. This second time, `super.populateTransaction` is called again but because `gasPrice` has been added in addition to the EIP fields, it throws `TypeError: eip-1559 transaction do not support gasPrice`.
In my …

fix: wallet.sendTransaction with customData incorrectly throwing TypeError

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/validate.yml
src/adapters.ts
src/contract.ts
src/provider.ts
src/signer.ts
src/utils.ts
src/wallet.ts
tests/integration/contract.test.ts
tests/integration/paymaster.test.ts
tests/integration/provider.test.ts
tests/integration/wallet.test.ts
tests/unit/signer.test.ts
tests/unit/util.test.ts
tsconfig.json

* Fix validation errors when populating a transaction when `maxFeePerGas` or `maxPriorityFeePerGas` are set. Populating a transaction calls for `ethers` implementation to check the type of transaction it is, whether it's EIP1559, by checking if `maxFeePerGas` and `maxPriorityFeePerGas` are set. If it is, it doesn't allow `gasPrice` to be present.

Make `populateTransaction` compatible with `ethers` validation

---

src/provider.ts

* Remove deprecated `Provider.getTokenPrice()`and `Provider.getMessageProof()` methods.

Ethers v5: Remove deprecations

---

src/signer.ts

* Fix example in `Signer.from()` method.

Ethers V6:  fix example in `Signer.from()` method

---

src/adapters.ts
tests/integration/wallet.test.ts

* `AdapterL1,getFullRequiredDepositFee` takes into account `tx.overrides.from`.
* This is useful when fee needs to be calculated  for address which private key is not known. The idea is to create random `Wallet` and override `from` field.
```ts
const randomWallet = new Wallet(
ethers.Wallet.createRandom().privateKey,
provider,
ethProvider
);
const result = await randomWallet.getFullRequiredDepositFee({
token: utils.ETH_ADDRESS,
to: RECEIPT,
overrides: { from: ADDRESS }
});
```

Eethers V6: make `AdapterL1.getFullRequiredDepositFee` work with overrides

---

src/index.ts
src/signer.ts
src/wallet.ts
tests/integration/signer.test.ts
tests/integration/wallet.test.ts

* Add `L2VoidSigner` and `L1VoidSigner`.
In certain scenarios, you may not possess the private key of an account but have its address and wish to utilize zksync read operations (such as `getFullDepositFee`, `isWithdrawalFinalized`, etc.). Currently, all signers (`Wallet`, `Signer`, `L1Signer`, and `EIP712Signer`) require a private key to function, and there is no way to bypass this requirement.
One approach is to modify Adapters' read operations to consider the `overrides.from` field as the account initiating the operation. However, this conflicts with the design of signers. All signers are intended to possess a private key, and the initiator of all operations is the account associated with that private key. The code is structured accordingly, and accommodating `overrides.from` would …

Ethers V5: Add `L2VoidSigner` and `L1VoidSigner`

---

src/index.ts
src/signer.ts
src/wallet.ts
tests/integration/signer.test.ts

* Add `L2VoidSigner` and `L1VoidSigner`
In certain scenarios, you may not possess the private key of an account but have its address and wish to utilize zksync read operations (such as `getFullDepositFee`, `isWithdrawalFinalized`, etc.). Currently, all signers (`Wallet`, `Signer`, `L1Signer`, and `EIP712Signer`) require a private key to function, and there is no way to bypass this requirement.
One approach is to modify Adapters' read operations to consider the `overrides.from` field as the account initiating the operation. However, this conflicts with the design of signers. All signers are intended to possess a private key, and the initiator of all operations is the account associated with that private key. The code is structured accordingly, and accommodating `overrides.from` would …

Ethers V6: Add `L2VoidSigner` and `L1VoidSigner`

---

src/adapters.ts
tests/integration/wallet.test.ts

This reverts commit `9feb1e136335f31b7eda3b2e9ef664b1e29ad366`.
Remove support from `AdapterL1.getFullRequiredDepositFee` for considering `overrides.from` as the initiator of the operation. This functionality was previously used to calculate the full deposit fee for accounts whose private key is unknown. However, this feature is no longer necessary because `L1VoidSigner.getFullRequiredDepositFee` is specifically designed to handle such cases.

Ethers V6: Remove support from `AdapterL1.getFullRequiredDepositFee` work wiith `overrides`

---

src/paymaster-utils.ts
src/utils.ts
tests/integration/contract.test.ts
tests/integration/paymaster.test.ts
tests/integration/provider.test.ts
tests/integration/signer.test.ts
tests/integration/wallet.test.ts
tests/setup.ts
tsconfig.json

* Ethers V5:  Replace `require` with `import`.
* It's best practice to use ECMAScript standard since TypeScript is configured to build to ES2019.

Ethers V5:  Replace `require` with `import`

---

src/signer.ts
src/utils.ts
src/wallet.ts
tests/unit/util.test.ts

* Fix `applyL1ToL2Alias` and `undoL1ToL2Alias` to always return 20 bytes long address by padding zeros to left.

Ethers V5: Fix `applyL1ToL2Alias` and `undoL1ToL2Alias` to always return 20 bytes long address

---

src/signer.ts
src/utils.ts
src/wallet.ts
tests/unit/utils.test.ts

* Fix `applyL1ToL2Alias` and `undoL1ToL2Alias` to always return 20 bytes long address by padding zeros to left.

Ethers Vg: Fix `applyL1ToL2Alias` and `undoL1ToL2Alias` to always return 20 bytes long address

---

src/format.ts
src/provider.ts
tests/integration/format.test.ts
tests/integration/provider.test.ts
yarn.lock

* Prefetched transactions were not created correctly in `Block` object. This PR solves this issue.

Ethers V6: Create prefetched txs correctly in `Block` object

---

src/provider.ts

* Parse all block fields from RPC endpoints.

Ethers V5:  Parse all block fields from RPC endpoints

---

src/adapters.ts

Updates the `l2TokenAddress` function in `adapter.ts`.
It was causing an error since it was calling to the `l2TokenAddress` in non existing contract.

fix: l2TokenAddress function in adapter

---

src/provider.ts
src/types.ts

* Add support for Era Test Node.
* Disable caching for local networks.

Ethers V6: Add support for Era Test Node and disable caching for local networks

---

src/provider.ts
yarn.lock

* Remove the support for the `ZKSYNC_WEB3_API_URL` in `Provider.getDefaultProvider`.
* Getting environment variable using `process.env` is only available on `Node.js` and it's not compatible with browsers.

Ethers V6: remove support for the `ZKSYNC_WEB3_API_URL` environment variable

---

src/provider.ts

* Remove the support for the `ZKSYNC_WEB3_API_URL` in `Provider.getDefaultProvider`.
* Getting environment variable using `process.env` is only available on `Node.js` and it's not compatible with browsers.

Ethers V5: Remove support for the `ZKSYNC_WEB3_API_URL` environment variable

---

src/provider.ts
src/types.ts

* Add support for era test node.

Ethers V5: Add support for era test node

---

src/adapters.ts

* Fix error in amount parameter description for deposit.

Ethers V5: fix error in amount parameter description for deposit

---

src/adapters.ts
src/utils.ts
tests/integration/wallet.test.ts
tests/setup.ts

* Updated request execute function
* for non-ETH base token msg.value should be 0

Ethers V5: provide correct msg.value for requestExecute (non-ETH base token)

---

src/utils.ts

- Default gas per pubdata signed increased to 2^32 - 1
- To support broader range of gas per pubdata supported by the future protocol versions

increase default gas per pubdata

---

src/provider.ts
tests/integration/provider.test.ts

* Drop support for the `Goerli` network.

Ethers V6: Drop support for the `Goerli` network

---

src/provider.ts
src/types.ts
src/wallet.ts
tests/integration/provider.test.ts

* Drop support for `Goerli` network.
* Fix typing for `TransactionResponse.wait()` and `Wallet.sendTransaction()` methods.

Ethers V5: Drop support for `Goerli` network and fix typing

---

src/provider.ts
src/types.ts
tests/integration/provider.test.ts

* Remove goerli from SDK 
* Goerli support has been deprecated both by Ethereum and by ZkSync

Ethers V5: Remove Goerli

---

src/signer.ts
src/wallet.ts

* Add support for RPC methods from `zks` namespace in `Signer`. Previously, whenever any `zks` method was called from `Signer` the `method not found` error was produced.

Ethers V6: Add support for `zks` RPC method in  `Signer`

---

src/index.ts

* Exports typechain as `contracts` namespace in order to provider easier interaction with common contracts.

Ethers V6: Add `contracts` namespace which exports typechain

---

src/signer.ts
src/wallet.ts

* Add support for `zks` RPC methods in `Signer`.

Ethers V5: Add support for `zks` RPC methods in `Signer`

---

src/adapters.ts

* Updated mintValue calculation for `getRequestExecuteTx`
* We would like the SDK to automatically estimate the l2 costs for both ETH and non-ETH based chains

provide default mint value for non-eth based chains requestExecute tx

---

src/adapters.ts
src/provider.ts
src/signer.ts
src/types.ts
src/utils.ts
tests/integration/signer.test.ts
tests/integration/wallet.test.ts
tests/setup.ts

* Use `isAddressEq` when comaparing addresses.

Ethers V6: Use `isAddressEq` when comaparing addresses

---

src/utils.ts
tests/integration/provider.test.ts
tests/integration/signer.test.ts
tests/integration/smart-account.test.ts
tests/integration/utils.test.ts
tests/integration/wallet.test.ts

* Fix the bug when `ETH_ADDRESS` is passed to `estimateDefaultBridgeDepositL2Gas` on non-ETH-based chain. The bug is resolved by converting `ETH_ADDRESS` to `ETH_ADDRESS_IN_CONTRACT` .

Ethers V6: Resolve bug when `ETH_ADDRESS` is passed to `estimateDefaultBridgeDepositL2Gas`

---

package.json
src/signer.ts

* Make `Signer` compatible when created using `Web3Provider.getSigner()`

Ethers V5:  Make `Signer` compatible when created using `Web3Provider.getSigner()`

---

package.json
src/signer.ts

* Make `Signer` compatible when created using `Web3Provider.getSigner()`

Ethers V6: Make Signer compatible when created using `Web3Provider.getSigner()`

---

src/provider.ts
tests/unit/provider.test.ts

* This fixes a bug in the provider method `getPriorityOpResponse`. Before, the `waitL1Commit` of the result object would have been `undefined`.
*  I noticed while debugging a project using zksync-ethers that the `waitL1Commit` function is not defined after bridging ERC20 from L1 (Sepolia) to L2. We can also verify this by running the test in this PR and using the old code, it would fail (the mentioned function is undefined). With the spread operator, anything from the object's prototype will not be included.
Please see the included test, it can be run with the old code and would fail, which is not the intended result.
Thanks a lot for taking a look.

Fix: getPriorityOpResponse correctly assigns waitL1Commit to l2Response object

---

.github/workflows/test.yml
.gitignore
package.json
src/paymaster-utils.ts
src/provider.ts
src/signer.ts
src/smart-account-utils.ts
src/smart-account.ts
src/wallet.ts
tests/files/tokens.json
tests/integration/wallet.test.ts
tests/setup.ts

* Export `typechain` folder at the top of the package.
* Make `Signer` compatible when created using `BrowserProvider.getSigner()`.

Ethers V6: Fix compatibility issues

---

package.json
scripts/update-diamond-proxy.sh
src/adapters.ts
src/contract.ts
src/provider.ts
src/smart-account-utils.ts
src/types.ts
src/utils.ts
tests/integration/signer.test.ts
tests/integration/types.test.ts
tests/integration/wallet.test.ts

* `FullDepositFee` uses `bigint` instead of `BigInt`.
* `Provider.getTransactionReceipt()` now returns `null` it transaction is not mined, not found or discarded.
* `Block.l1BatchTimestamp` now contains accurate value.

Ethers V6: Fix types and provider

---

.eslintignore
.gitignore
.prettierignore
package.json

* build ESM module assets into `/build-esm` folder during the building process
* add `build-esm/index.js` to the "module" filed of package.json
* add `build-esm` folder into `.gitignore`
* When calling `import {..} from "zksync-ethers"`, the `zksync-ethers` package will export an ESM module instead of a CommonJS module.
* ESM modules benefit from tree shaking, which can result in smaller and more optimized bundles.
* The `ethers` package exports both ESM and CommonJS modules; `zksync-ethers` could follow the same pattern

build: support esm module

---

tests/integration/smart-account.test.ts
tests/integration/wallet.test.ts

* Use `utils.L2_BASE_TOKEN_ADDRESS` as a address when working with base token.

Ethers V6: test: use `utils.L2_BASE_TOKEN_ADDRESS` as a address when working with base token

---

tests/integration/smart-account.test.ts
tests/integration/wallet.test.ts

* Use `utils.L2_BASE_TOKEN_ADDRESS` as a address when working with base token.

Ethers V5: test: use `utils.L2_BASE_TOKEN_ADDRESS` as a address when working with base token

---

src/adapters.ts
src/provider.ts
tests/integration/provider.test.ts
tests/integration/smart-account.test.ts
tests/integration/wallet.test.ts

* Use `utils.L2_BASE_TOKEN_ADDRESS` as a address when working with base token.

Ethers V6: refactor(provider): use `utils.L2_BASE_TOKEN_ADDRESS` as a address when working with base token

---

package.json
src/adapters.ts
src/provider.ts
src/signer.ts
src/types.ts
src/utils.ts
src/wallet.ts
tests/integration/provider.test.ts
tests/unit/utils.test.ts

* Add new rpc endpoints to `Provider` class.
* Add missing examples.

Ethers V6:  Add new rpc endpoints

---

.github/workflows/test.yml
src/adapters.ts
src/provider.ts
src/signer.ts
src/types.ts
src/utils.ts
src/wallet.ts
tests/integration/provider.test.ts

* Align types and RPC API with version `v24.7.0` of ZKsync node.

Ethers V5:  Align types and RPC API with version `v24.7.0` of ZKsync node

---

src/adapters.ts
src/types.ts

Use erc20 bridge addresses if weth bridge addresses are not present.
Currently weth bridge addresses are required, and getL1BridgeContracts/getL2BridgeContracts function fails.
This should fix deposits to the chains with custom base token.

fix: make weth bridge addresses optional

---

package.json

What 💻
Set the value of option "sideEffects" in package.json to false.
Same as what ethers.js does: https://github.com/ethers-io/ethers.js/blob/main/package.json
Why ✋
There are bundled frontend applications that use zksync-ethers. This option will enable tree shaking. Bundles can be organized more efficiently, and in most cases less code will be fetched and parsed by clients, so performance can be improved.
Evidence 📷
Find more about the option here: https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects

chore: set value of sideEffects to false

---

src/provider.ts

Include `customData.customSignature` in `estimateGas` calls.
Without it, it is very hard to properly estimate gas for AA accounts with complex validation logic. But also, there is no reason not to include it, I don't know why it was omitted before.
Correctly estimated gas for AA with complex validation logic:

fix: include custom signature in estimateGas calls

---

.github/workflows/docs.yml
.github/workflows/publish.yml

* Workflow for publishing docs (`docs.yml`) could be run from user outside of collaborators without approval. The following PR fixes it.
* The publishing docs is added to workflow that publish the package to NPM in order to automate the docs publishing after successful package publishing.

ci: fix running workflow without approval

---

.github/workflows/docs.yml
.github/workflows/publish.yml

* Add the permissions for publishing docs in `publish` workflow.
* Use only `inputs.ref` in `docs` workflow.

ci: fix permissions for publishing docs

---

src/adapters.ts
src/provider.ts
src/smart-account.ts

Deprecates a few legacy methods from `zks` namespace that are about to be removed
After analyzing usefulness and usage patterns we decided to remove some of them methods from `zks` namespace

feat: deprecate legacy `zks` methods

---

src/adapters.ts
src/provider.ts
src/types.ts
src/utils.ts
src/wallet.ts
tests/setup.ts
tests/tokens.json

Adds interop support by modifying the existing `getLogProof` to accept an additional parameter, `interopMode`, to specify the target Merkle root for the interop Merkle proof. This is done in a backwards-compatible way while also ensuring future interop modes (proof based on L1, commit based, ...) can be easily added.
This PR is associated with: https://github.com/matter-labs/zksync-era/pull/4130

feat: interop support

---

src/provider.ts
src/signer.ts
src/smart-account-utils.ts
src/utils.ts
src/wallet.ts

This PR replaces all usages of `zks_estimateFee` in favour of `eth_estimateGas` + `eth_gasPrice` + `zks_gasPerPubdata` (new method, won't be available on _all_ envs for a bit).
Benefit of this is that we won't wait for gas limit to be estimated if all we want is just current gas price or gas per pubdata.
Also, `zks_estimateFee` is scheduled for deprecation soon so its important to start reducing its usage.

feat: avoid `zks_estimateFee` for populating fee data

---

abi/IBridgehub.json
abi/IL1AssetRouter.json
abi/IL1NativeTokenVault.json
abi/IL1Nullifier.json
abi/IL2AssetRouter.json
abi/IL2NativeTokenVault.json
src/adapters.ts
src/provider.ts
src/typechain/IBridgehub.ts
src/typechain/IL1AssetRouter.ts
src/typechain/IL1NativeTokenVault.ts
src/typechain/IL1Nullifier.ts
src/typechain/IL2AssetRouter.ts
src/typechain/IL2NativeTokenVault.ts
src/typechain/factories/IBridgehub__factory.ts
src/typechain/factories/IL1AssetRouter__factory.ts
src/typechain/factories/IL1NativeTokenVault__factory.ts
src/typechain/factories/IL1Nullifier__factory.ts
src/typechain/factories/IL2AssetRouter__factory.ts
src/typechain/factories/IL2NativeTokenVault__factory.ts
tests/integration/provider.test.ts
tests/integration/signer.test.ts
tests/integration/smart-account.test.ts
tests/integration/wallet.test.ts

To address the changes mentioned in #253, the SDK will need a more significant redesign to properly handle the challenges encountered when relying on on-chain data instead of RPC methods.
The core issue is that the Provider was originally designed only to interact with L2 nodes via RPC calls to retrieve necessary L1 data. As a result, it cannot communicate with the Bridgehub (deployed on L1) to fetch bridge and token addresses. This limitation breaks nearly all Provider methods related to bridging. The following methods are no longer supported:
- `l2TokenAddress`, 
- `l1TokenAddress`, 
- `getWithdrawTx`, 
- `estimateDefaultBridgeDepositL2Gas`, 
- `estimateCustomBridgeDepositL2Gas`, 
- `getMainContractAddress`, 
- `getBaseTokenContractAddress`, 
- `getL2TransactionFromPriorityOp`, 
- …

fix: use onchain data instead of RPC endpoints
