- src/provider.ts
- tests/integration/provider.test.ts
Removes the getConfirmedTokens from ethers v5 based version.
Brother of #4 .
Same as #4 
> feat(ethers v5): Remove getConfirmedTokens method

- README.md
* Add zkSync logo
* To look nicer.
> docs(README): add zkSync logo

- .github/workflows/validate.yml
* Add conditional step in validation pipeline that checks commit messages from fork repositories.
* Contributors needs to follow conventional commits.
> ci: configure `commitlint` to check commits from forks

- scripts/entrypoint.sh
- src/adapters.ts
- src/provider.ts
- src/utils.ts
and files that need to be copied
> updated with base token changes

- .github/workflows/test.yml
- src/adapters.ts
- src/contract.ts
- src/provider.ts
- src/signer.ts
- src/utils.ts
- src/wallet.ts
- tests/integration/contract.test.ts
- tests/integration/provider.test.ts
- tests/integration/wallet.test.ts
- tests/unit/signer.test.ts
- tests/unit/util.test.ts
* Fix typo in parameters related to paymster params.
* Align error message to follow same format.
> feat(provider, wallet): fix typo in paymaster parameter name

- README.md
* Add Google Typescript style badge
> Add Google Typescript style badge

- src/adapters.ts
- src/provider.ts
- src/signer.ts
- src/types.ts
- src/utils.ts
- src/wallet.ts
- tests/integration/format.test.ts
- tests/integration/provider.test.ts
- tests/integration/types.test.ts
- tests/integration/wallet.test.ts
- tests/unit/signer.test.ts
- tests/unit/utils.test.ts
* Populate all transaction types (inlcuding legacy and EIP1559) before signing.
> Populate all transaction types before signing

- .gitignore
- package.json
- scripts/post-process-doc.sh
- src/adapters.ts
- src/contract.ts
- src/paymaster-utils.ts
- src/provider.ts
- src/signer.ts
- src/types.ts
- src/utils.ts
- src/wallet.ts
- typedoc.json
- yarn.lock
* Document the source code.
* Add `typedoc` tool for generating documentation in markdown files.
* Add `utils.toJSON` function for printing objects.
> Ethers v5 document the source code

- src/adapters.ts
- src/paymaster-utils.ts
- src/provider.ts
- src/signer.ts
- src/utils.ts
* Fix the errors in documentation.
> Ethers V6: fix the errors in documentation.

- src/wallet.ts
- tests/integration/signer.test.ts
> Ethers V5: Fix errors in tests

- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- src/provider.ts
* Update action version in workflows.
* In order to remove deprecation warnings in CI.
> Ethers V6: Update action version in workflows

- build/src/adapters.d.ts
- build/src/adapters.js
- build/src/signer.d.ts
- build/src/wallet.d.ts
* Adds the result of running `npm run build`.
* It includes the build files that are generated from the following commits:
- https://github.com/zksync-sdk/zksync-ethers/commit/13aecc799938ad55375e16bac45e0ad4be585c29
- https://github.com/zksync-sdk/zksync-ethers/commit/9ad328cef96746b1b999bced90689cd83d3d1683
* A couple changes were merged without the build files, causing the changes
> Fix(Bridgehub): add missing builds

- src/adapters.ts
* fix error in amount parameter description for deposit
> Ethers V6: fix error in amount parameter description for deposit

- src/signer.ts
> Ethers V6: fix errors in docs

- abi/IBridgehub.json
- abi/IContractDeployer.json
- abi/IZkSyncStateTransition.json
- build/abi/IBridgehub.json
- build/abi/IContractDeployer.json
- build/abi/IZkSyncStateTransition.json
- build/typechain/IBridgehub.d.ts
- build/typechain/IBridgehubFactory.js
- build/typechain/IContractDeployer.d.ts
- build/typechain/IZkSyncStateTransition.d.ts
- build/typechain/IZkSyncStateTransitionFactory.js
- typechain/IBridgehub.d.ts
- typechain/IBridgehubFactory.ts
- typechain/IContractDeployer.d.ts
- typechain/IContractDeployerFactory.ts
- typechain/IZkSyncStateTransition.d.ts
- typechain/IZkSyncStateTransitionFactory.ts
Updated contract ABIs
They were outdated
> feat: Update contract ABIs

- build/src/provider.js
- src/provider.ts
> changed rpc points

- src/signer.ts
* Fix errors in documentation.
> Ethers V6: Fix errors in documentation

- src/signer.ts
* Fix errors in documentation.
> Ethers V5: Fix errors in documentation

- src/signer.ts
> Ethers V6:  Fix errors in `Signer`

- build/src/adapters.js
- build/src/provider.js
- build/src/types.d.ts
- build/src/types.js
- src/adapters.ts
- src/provider.ts
> renamed rpc url

- build/src/adapters.js
- build/src/utils.d.ts
- build/src/utils.js
- src/adapters.ts
- src/utils.ts
> modified deposit tx gas estimate

- build/src/wallet.js
- src/wallet.ts
> populate legacy tx remove gasPrice

- build/src/provider.d.ts
- build/src/provider.js
- src/provider.ts
> Add function to get base token

- build/src/provider.d.ts
- build/src/provider.js
- src/provider.ts
Reverts zksync-sdk/zksync-ethers#125
> Revert "Add function to get base token"

- src/adapters.ts
> Lowercase comparison of addresses

- build/src/adapters.js
> build branch

- build/src/adapters.js
- build/src/provider.js
- build/src/utils.d.ts
- build/src/utils.js
- build/src/wallet.js
- src/adapters.ts
- src/provider.ts
- src/utils.ts
- src/wallet.ts
> Always use correct address comparison

- build/src/adapters.js
- build/src/provider.js
- build/src/wallet.js
- src/adapters.ts
- src/provider.ts
- src/wallet.ts
Check addresses only if they are not null
> Check only if token is not null

- src/adapters.ts
- src/provider.ts
- src/signer.ts
- src/utils.ts
- tests/integration/signer.test.ts
* Use `isAddressEq` when comparing addresses.
> Ethers V5: Use `isAddressEq` when comparing addresses

- .github/workflows/test.yml
- tests/integration/signer.test.ts
- tests/integration/smart-account.test.ts
- tests/integration/wallet.test.ts
- tests/setup.ts
* Adding CI with new local setup
> feat: add CI to ethers-v5-beta

- tests/integration/wallet.test.ts
* Adding a proper waiting condition in the claim test.
* Before we were waiting blindly for 10 seconds, which was flaky.
* Now we actually wait for the correct condition (block being in the executed state).
> fix: Fixing EVM-568 - wait properly for the block to be executed on l1

- .github/workflows/test.yml
- src/adapters.ts
- src/provider.ts
- src/signer.ts
- src/wallet.ts
- tests/files/tokens.json
- tests/integration/provider.test.ts
- tests/integration/signer.test.ts
- tests/integration/smart-account.test.ts
- tests/integration/types.test.ts
- tests/integration/utils.test.ts
- tests/integration/wallet.test.ts
- tests/setup.ts
* Resolve compatibility issues
> Ethers V6: resolve compatibility issues

- package.json
* Resolve module resolution for `typechain` definition files.
> Ethers V5:  Resovle typechain definitions

- .github/workflows/test.yml
- tests/integration/account-abstraction.test.ts
- tests/integration/contract.test.ts
- tests/integration/format.test.ts
- tests/integration/provider.test.ts
- tests/integration/signer.test.ts
- tests/integration/smart-account.test.ts
- tests/integration/types.test.ts
- tests/integration/utils.test.ts
- tests/integration/wallet.test.ts
- tests/setup.ts
- tests/unit/smart-account.test.ts
- tests/utils.ts
> Ethers V6: test: migrate to hyperchain setup

- .github/workflows/test.yml
- tests/integration/account-abstraction.test.ts
- tests/integration/contract.test.ts
- tests/integration/provider.test.ts
- tests/integration/signer.test.ts
- tests/integration/smart-account.test.ts
- tests/integration/utils.test.ts
- tests/integration/wallet.test.ts
- tests/setup.ts
- tests/unit/smart-account.test.ts
- tests/utils.ts
* Migrate to hyperchain setup.
> Ethers V5: test: migrate to hyperchain setup

- src/types.ts
* Update `RawBlockTransaction`.
> Ethers V5: fix(types): update `RawBlockTransaction`

- src/types.ts
* Update `RawBlockTransaction`.
> Ethers V6: fix(types): update `RawBlockTransaction`

- abi/IBridgehub.json
- abi/IContractDeployer.json
- abi/IL1ERC20Bridge.json
- abi/IL1SharedBridge.json
- abi/IL2SharedBridge.json
- abi/IZkSyncHyperchain.json
- scripts/entrypoint.sh
- src/adapters.ts
- src/signer.ts
- src/typechain/IBridgehub.d.ts
- src/typechain/IBridgehubFactory.ts
- src/typechain/IContractDeployer.d.ts
- src/typechain/IContractDeployerFactory.ts
- src/typechain/IZkSyncHyperchain.d.ts
- src/typechain/IZkSyncHyperchainFactory.ts
- src/typechain/Il1Erc20Bridge.d.ts
- src/typechain/Il1Erc20BridgeFactory.ts
- src/typechain/Il1SharedBridge.d.ts
- src/typechain/Il1SharedBridgeFactory.ts
- src/typechain/Il2SharedBridge.d.ts
- src/typechain/Il2SharedBridgeFactory.ts
- src/utils.ts
- src/wallet.ts
> Ethers V5: refactor: update typechain

- README.md
* Fix broken link to official documentation.
> Ethers V6: docs(README): update broken link

- README.md
- package.json
- tests/integration/wallet.test.ts
* Fix broken link to official documentation.
> Ethers V5: docs(README): fix broken link to official documentation

- .github/workflows/test.yml
* Build package before running tests
> Ethers V6: ci(test): build package before running tests

- src/provider.ts
- yarn.lock
* Bump `ethers` to version `v6.13.1` to fix vulnerabilities.
> build(deps): bump `ethers` to `v6.13.1`

- README.md
* Fixed link in readme
* It was broken
> fix: link to docs in readme

- src/provider.ts
- src/signer.ts
* Fix errors in documentation.
> docs: fix errors

- src/adapters.ts
- src/signer.ts
- src/wallet.ts
This PR fixes: https://github.com/zksync-sdk/zksync-ethers/issues/234
> feat(adapter): add `overrides` param to `getDepositAllowanceParams`

- .github/workflows/test.yml
- .github/workflows/validate.yml
> fix: address ci branch
